spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bank
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

# Flyway config (keep enabled)
flyway:
  enabled: true
  locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "*"
