apiVersion: v1
kind: Service
metadata:
  name: ms-clients-service
  labels:
    app: ms-clients
spec:
  type: ClusterIP
  selector:
    app: ms-clients
  ports:
    - name: http
      port: 80
      targetPort: 8080
