apiVersion: v1
kind: Service
metadata:
  name: ms-account-service
  labels:
    app: ms-account
spec:
  type: ClusterIP
  selector:
    app: ms-account
  ports:
    - name: http
      port: 80
      targetPort: 8080
